/** Texture keys. Swap the generators in src/art for real sprite sheets later. */
export const TEX = {
  wood: 'desk-wood',
  lamp: 'desk-lamp',
  lampLight: 'desk-lamp-light',
  vignette: 'desk-vignette',
  mug: 'desk-mug',
  steam: 'desk-steam', // + frame index
  folderStack: 'desk-folder-stack',
  folder: 'desk-folder',
  inkPad: 'desk-inkpad',
  stampRug: 'desk-stamp-rug',
  stampLegit: 'desk-stamp-legit',
  corkboard: 'desk-corkboard',
  window: 'desk-window',
  windowLights: 'desk-window-lights', // + frame index
  windowFlash: 'desk-window-flash',
  raindrop: 'desk-raindrop',
  cat: 'desk-cat', // + frame index
  heart: 'desk-heart',
  steamPuff: 'desk-steam-puff',
  clock: 'desk-clock',
  paper: 'paper-sheet',
  paperSmall: 'paper-sheet-small',
  paperclip: 'paper-clip',
  coffeeRing: 'paper-coffee-ring',
  pin: 'paper-pin',
  pinStray: 'paper-pin-stray',
  tab: 'paper-tab',
  tabActive: 'paper-tab-active',
  cursor: 'mag-cursor',
  lensRim: 'mag-lens-rim',
  lensRimGlow: 'mag-lens-rim-glow',
  lensVignette: 'mag-lens-vignette',
  lensGlint: 'mag-lens-glint',
  iconCheck: 'icon-check',
  iconCross: 'icon-cross',
  iconWarn: 'icon-warn',
  iconLock: 'icon-lock',
  iconUnlock: 'icon-unlock',
  iconPadlock: 'icon-padlock',
  iconPie: 'icon-pie',
  pixel: 'px-white',
  drawer: 'cabinet-drawer',
  button: 'ui-button',
  buttonHover: 'ui-button-hover',
} as const;

export const STEAM_FRAMES = 3;
export const portraitKey = (seed: string): string => `portrait-${seed}`;
